plugins {
    id 'com.android.application'
}

android {
    namespace 'com.toolfizz.quotationmaker'
    compileSdk 35

    defaultConfig {
        applicationId "com.toolfizz.quotationmaker"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            applicationIdSuffix ""
            versionNameSuffix ""
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
